export interface LanguageOption {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

export const INDIAN_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: '🚩' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
];

export interface TranslationSet {
  selectRole: string;
  selectRoleSub: string;
  citizenRole: string;
  citizenDesc: string;
  adminRole: string;
  adminDesc: string;
  workerRole: string;
  workerDesc: string;
  enterPortal: string;
  switchRole: string;
  darkMode: string;
  lightMode: string;
  language: string;
  settings: string;
  ecoPulse: string;
  ecoPulseMsg: string;
  // Menu items
  overview: string;
  dashboard: string;
  analytics: string;
  reportWaste: string;
  myGrievances: string;
  liveTracker: string;
  weeklySchedule: string;
  greenPoints: string;
  segregationGuide: string;
  grievanceDispatch: string;
  fleetManagement: string;
  workerRegistry: string;
  zoneManagement: string;
  auditReports: string;
  platformSettings: string;
  myDashboard: string;
  myRouteMap: string;
  binChecklist: string;
  shiftHistory: string;
  workerProfile: string;
  // Actions & Labels
  contactSupport: string;
  viewReports: string;
  exportPdf: string;
  generateInsights: string;
  reportWasteNow: string;
  wasteDiverted: string;
  recycling: string;
  compost: string;
  landfill: string;
  activeRoutes: string;
  nextCollection: string;
  sustainabilityImpact: string;
  recentActivity: string;
  carbonOffset: string;
  waterSaved: string;
}

export const UI_TRANSLATIONS: Record<string, TranslationSet> = {
  en: {
    selectRole: 'Select Your Role',
    selectRoleSub: 'Welcome to Nagpur SmartSanitation. Choose your portal to proceed.',
    citizenRole: 'Citizen Portal',
    citizenDesc: 'Report waste grievances, track truck location, earn GreenPoints rewards & view schedule.',
    adminRole: 'Admin Portal',
    adminDesc: 'Municipal oversight, fleet monitoring, grievance dispatch, and zone analytics.',
    workerRole: 'Worker Portal',
    workerDesc: 'Sanitation worker route navigation, bin collection confirmation, and shift logs.',
    enterPortal: 'Enter Portal',
    switchRole: 'Switch Role',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    settings: 'Settings',
    ecoPulse: 'Eco Pulse',
    ecoPulseMsg: 'Nagpur targets 100% diversion by 2026.',
    overview: 'Overview',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    reportWaste: 'Report Waste',
    myGrievances: 'My Grievances',
    liveTracker: 'Live Truck Tracker',
    weeklySchedule: 'Weekly Timetable',
    greenPoints: 'GreenPoints Rewards',
    segregationGuide: 'Segregation Guide',
    grievanceDispatch: 'Grievance Dispatch',
    fleetManagement: 'Fleet Management',
    workerRegistry: 'Worker Registry',
    zoneManagement: 'Zone Management',
    auditReports: 'Audit Reports',
    platformSettings: 'Platform Settings',
    myDashboard: 'My Dashboard',
    myRouteMap: 'My Route Map',
    binChecklist: 'Bin Checklist',
    shiftHistory: 'Shift History',
    workerProfile: 'Worker Profile',
    contactSupport: 'Contact Support',
    viewReports: 'View Reports',
    exportPdf: 'Export PDF',
    generateInsights: 'Generate Insights',
    reportWasteNow: 'Report Waste Now',
    wasteDiverted: 'Waste Diverted',
    recycling: 'Recycling',
    compost: 'Compost',
    landfill: 'Landfill',
    activeRoutes: 'Active Routes',
    nextCollection: 'Next Collection Status',
    sustainabilityImpact: 'Sustainability Impact',
    recentActivity: 'Recent Activity',
    carbonOffset: 'Carbon Offset',
    waterSaved: 'Water Saved',
  },
  hi: {
    selectRole: 'अपनी भूमिका चुनें',
    selectRoleSub: 'नागपुर स्मार्ट सैनिटेशन में आपका स्वागत है। आगे बढ़ने के लिए अपना पोर्टल चुनें।',
    citizenRole: 'नागरिक पोर्टल',
    citizenDesc: 'कचरा शिकायतों की रिपोर्ट करें, ट्रक ट्रैक करें, ग्रीनपॉइंट्स कमाएं और समय सारणी देखें।',
    adminRole: 'प्रशासनिक पोर्टल',
    adminDesc: 'नगर निगम निगरानी, बेड़े की ट्रैकिंग, शिकायत निवारण और ज़ोन विश्लेषण।',
    workerRole: 'कर्मचारी पोर्टल',
    workerDesc: 'सफाई कर्मचारी मार्ग नेविगेशन, बिन संग्रह पुष्टि और शिफ्ट लॉग।',
    enterPortal: 'पोर्टल में प्रवेश करें',
    switchRole: 'भूमिका बदलें',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    settings: 'सेटिंग्स',
    ecoPulse: 'इको पल्स',
    ecoPulseMsg: 'नागपुर का लक्ष्य 2026 तक 100% कचरा परिवर्तन है।',
    overview: 'अवलोकन',
    dashboard: 'डैशबोर्ड',
    analytics: 'विश्लेषण',
    reportWaste: 'कचरा रिपोर्ट करें',
    myGrievances: 'मेरी शिकायतें',
    liveTracker: 'लाइव ट्रक ट्रैकर',
    weeklySchedule: 'साप्ताहिक समय-सारणी',
    greenPoints: 'ग्रीनपॉइंट्स पुरस्कार',
    segregationGuide: 'कचरा पृथक्करण गाइड',
    grievanceDispatch: 'शिकायत निवारण',
    fleetManagement: 'वाहन बेड़ा प्रबंधन',
    workerRegistry: 'कर्मचारी पंजी',
    zoneManagement: 'ज़ोन प्रबंधन',
    auditReports: 'लेखा परीक्षा रिपोर्ट',
    platformSettings: 'मंच सेटिंग्स',
    myDashboard: 'मेरा डैशबोर्ड',
    myRouteMap: 'मेरा मार्ग मानचित्र',
    binChecklist: 'कचरा पेटियाँ जाँच सूची',
    shiftHistory: 'शिफ्ट इतिहास',
    workerProfile: 'कर्मचारी प्रोफाइल',
    contactSupport: 'सहायता से संपर्क करें',
    viewReports: 'रिपोर्ट देखें',
    exportPdf: 'पीडीएफ निर्यात करें',
    generateInsights: 'अंतर्दृष्टि उत्पन्न करें',
    reportWasteNow: 'अब कचरा रिपोर्ट करें',
    wasteDiverted: 'कचरा मोड़ा गया',
    recycling: 'पुनर्चक्रण',
    compost: 'कंपोस्ट खाद',
    landfill: 'लैंडफिल',
    activeRoutes: 'सक्रिय मार्ग',
    nextCollection: 'अगला संग्रह स्थिति',
    sustainabilityImpact: 'सतत प्रभाव',
    recentActivity: 'हाल की गतिविधि',
    carbonOffset: 'कार्बन ऑफसेट',
    waterSaved: 'जल बचाया गया',
  },
  mr: {
    selectRole: 'आपली भूमिका निवडा',
    selectRoleSub: 'नागपूर स्मार्ट सॅनिसेशनमध्ये आपले स्वागत आहे. पुढे जाण्यासाठी आपला पोर्टल निवडा.',
    citizenRole: 'नागरिक पोर्टल',
    citizenDesc: 'कचरा तक्रारी नोंदवा, कचरा गाडी ट्रॅक करा, ग्रीनपॉइंट्स मिळवा आणि वेळापत्रक पहा.',
    adminRole: 'प्रशासकीय पोर्टल',
    adminDesc: 'महानगरपालिका देखरेख, ताफा ट्रॅकिंग, तक्रार निवारण आणि विभाग विश्लेषण.',
    workerRole: 'कर्मचारी पोर्टल',
    workerDesc: 'स्वच्छता कर्मचारी मार्ग नेव्हिगेशन, कचरा कुंडी संकलन नोंद आणि शिफ्ट तपशील.',
    enterPortal: 'पोर्टलमध्ये प्रवेश करा',
    switchRole: 'भूमिका बदला',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा',
    settings: 'सेटिंग्ज',
    ecoPulse: 'इको पल्स',
    ecoPulseMsg: 'नागपूरचे २०२६ पर्यंत १००% कचरा विलीनीकरणाचे उद्दिष्ट आहे.',
    overview: 'आढावा',
    dashboard: 'डॅशबोर्ड',
    analytics: 'विश्लेषण',
    reportWaste: 'कचरा तक्रार नोंदवा',
    myGrievances: 'माझ्या तक्रारी',
    liveTracker: 'लाइव्ह ट्रक ट्रॅकर',
    weeklySchedule: 'साप्ताहिक वेळापत्रक',
    greenPoints: 'ग्रीनपॉइंट्स बक्षिसे',
    segregationGuide: 'कचरा वर्गीकरण मार्गदर्शक',
    grievanceDispatch: 'तक्रार निवारण',
    fleetManagement: 'गाड्यांचे व्यवस्थापन',
    workerRegistry: 'कर्मचारी नोंदणी',
    zoneManagement: 'विभाग व्यवस्थापन',
    auditReports: 'अहवाल',
    platformSettings: 'सिस्टम सेटिंग्ज',
    myDashboard: 'माझा डॅशबोर्ड',
    myRouteMap: 'माझा मार्ग नकाशा',
    binChecklist: 'कचराकुंडी यादी',
    shiftHistory: 'शिफ्ट इतिहास',
    workerProfile: 'कर्मचारी प्रोफाइल',
    contactSupport: 'संपर्क साधा',
    viewReports: 'अहवाल पहा',
    exportPdf: 'PDF डाऊनलोड करा',
    generateInsights: 'विश्लेषण करा',
    reportWasteNow: 'आत्ताच तक्रार करा',
    wasteDiverted: 'पुनर्वापर कचरा',
    recycling: 'पुनर्चक्रण',
    compost: 'कंपोस्ट',
    landfill: 'भूमीभरण',
    activeRoutes: 'सक्रिय मार्ग',
    nextCollection: 'पुढील संकलन वेळ',
    sustainabilityImpact: 'पर्यावरण प्रभाव',
    recentActivity: 'अलीकडील हालचाली',
    carbonOffset: 'कार्बन बचत',
    waterSaved: 'पाणी बचत',
  },
  bn: {
    selectRole: 'আপনার ভূমিকা নির্বাচন করুন',
    selectRoleSub: 'নাগপুর স্মার্ট স্যানিটেশনে স্বাগতম। এগিয়ে যেতে আপনার পোর্টাল চয়ন করুন।',
    citizenRole: 'নাগরিক পোর্টাল',
    citizenDesc: 'বর্জ্য অভিযোগ রিপোর্ট করুন, ট্রাক ট্র্যাক করুন, গ্রিনপয়েন্ট সংগ্রহ করুন।',
    adminRole: 'প্রশাসনিক পোর্টাল',
    adminDesc: 'পৌর পর্যবেক্ষণ, ফ্লিট ট্র্যাকিং এবং জোন বিশ্লেষণ।',
    workerRole: 'কর্মী পোর্টাল',
    workerDesc: 'পরিচ্ছন্নতা কর্মীদের রুট নেভিগেশন এবং বিন সংগ্রহ নিশ্চিতকরণ।',
    enterPortal: 'পোর্টাল প্রবেশ করুন',
    switchRole: 'ভূমিকা পরিবর্তন',
    darkMode: 'ডার্ক মোড',
    lightMode: 'লাইট মোড',
    language: 'ভাষা',
    settings: 'সেটিংস',
    ecoPulse: 'ইকো পালস',
    ecoPulseMsg: 'নাগপুরের লক্ষ্য ২০২৬ সালের মধ্যে ১০০% বর্জ্য অপসারণ।',
    overview: 'ওভারভিউ',
    dashboard: 'ড্যাশবোর্ড',
    analytics: 'বিশ্লেষণ',
    reportWaste: 'বর্জ্য রিপোর্ট করুন',
    myGrievances: 'আমার অভিযোগ',
    liveTracker: 'লাইভ ট্রাক ট্র্যাকার',
    weeklySchedule: 'সাপ্তাহিক সময়সূচী',
    greenPoints: 'গ্রিনপয়েন্টস পুরষ্কার',
    segregationGuide: 'বর্জ্য পৃথকীকরণ গাইড',
    grievanceDispatch: 'অভিযোগ নিষ্পত্তি',
    fleetManagement: 'যানবাহন ব্যবস্থাপনা',
    workerRegistry: 'কর্মী রেজিস্ট্রি',
    zoneManagement: 'জোন ব্যবস্থাপনা',
    auditReports: 'অডিট রিপোর্ট',
    platformSettings: 'প্ল্যাটফর্ম সেটিংস',
    myDashboard: 'আমার ড্যাশবোর্ড',
    myRouteMap: 'আমার রুট ম্যাপ',
    binChecklist: 'বিন চেকলিস্ট',
    shiftHistory: 'শিফট ইতিহাস',
    workerProfile: 'কর্মী প্রোফাইল',
    contactSupport: 'সহায়তা সমর্থন',
    viewReports: 'রিপোর্ট দেখুন',
    exportPdf: 'পিডিএফ রপ্তানি',
    generateInsights: 'ইনসাইট তৈরি করুন',
    reportWasteNow: 'এখনই রিপোর্ট করুন',
    wasteDiverted: 'পুনর্ব্যবহৃত বর্জ্য',
    recycling: 'পুনর্ব্যবহার',
    compost: 'কম্পোস্ট',
    landfill: 'ল্যান্ডফিল',
    activeRoutes: 'সক্রিয় রুট',
    nextCollection: 'পরবর্তী সংগ্রহের অবস্থা',
    sustainabilityImpact: 'স্থায়িত্ব প্রভাব',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    carbonOffset: 'কার্বন অফসেট',
    waterSaved: 'জল সাশ্রয়',
  },
  te: {
    selectRole: 'మీ పాత్రను ఎంచుకోండి',
    selectRoleSub: 'నాగ్‌పూర్ స్మార్ట్ శానిటేషన్‌కు స్వాగతం.',
    citizenRole: 'పౌరుల పోర్టల్',
    citizenDesc: 'చెత్త ఫిర్యాదులను నమోదు చేయండి, వాహనాన్ని ట్రాక్ చేయండి.',
    adminRole: 'పరిపాలనా పోర్టల్',
    adminDesc: 'మునిసిపల్ పర్యవేక్షణ, వాహనాల ట్రాకింగ్ మరియు విశ్లేషణ.',
    workerRole: 'కార్మికుల పోర్టల్',
    workerDesc: 'శుభ్రపరిచే సిబ్బంది రూట్ నావిగేషన్ మరియు సేకరణ ధృవీకరణ.',
    enterPortal: 'పోర్టల్‌లోకి ప్రవేశించండి',
    switchRole: 'పాత్రను మార్చండి',
    darkMode: 'డార్క్ మోడ్',
    lightMode: 'లైట్ మోడ్',
    language: 'భాష',
    settings: 'సెట్టింగ్‌లు',
    ecoPulse: 'ఈకో పల్స్',
    ecoPulseMsg: '2026 నాటికి 100% వ్యర్థాల తగ్గింపు నాగ్‌పూర్ లక్ష్యం.',
    overview: 'అవలోకనం',
    dashboard: 'డాష్‌బోర్డ్',
    analytics: 'విశ్లేషణలు',
    reportWaste: 'చెత్తను నివేదించండి',
    myGrievances: 'నా ఫిర్యాదులు',
    liveTracker: 'లైవ్ ట్రక్ ట్రాకర్',
    weeklySchedule: 'వారపు సమయ పట్టిక',
    greenPoints: 'గ్రీన్ పాయింట్లు',
    segregationGuide: 'చెత్త వేరుచేసే మార్గదర్శి',
    grievanceDispatch: 'ఫిర్యాదుల పరిష్కారం',
    fleetManagement: 'వాహనాల నిర్వహణ',
    workerRegistry: 'కార్మికుల జాబితా',
    zoneManagement: 'మండలాల నిర్వహణ',
    auditReports: 'నివేదికలు',
    platformSettings: 'సిస్టమ్ సెట్టింగ్‌లు',
    myDashboard: 'నా డాష్‌బోర్డ్',
    myRouteMap: 'నా రూట్ మ్యాప్',
    binChecklist: 'చెత్త డబ్బాల జాబితా',
    shiftHistory: 'షిఫ్ట్ చరిత్ర',
    workerProfile: 'కార్మికుని వివరాలు',
    contactSupport: 'మద్దతు పొందండి',
    viewReports: 'నివేదికలు చూడండి',
    exportPdf: 'PDF డౌన్‌లోడ్',
    generateInsights: 'విశ్లేషించండి',
    reportWasteNow: 'ఇప్పుడే నివేదించండి',
    wasteDiverted: 'మరల ఉపయోగించిన చెత్త',
    recycling: 'రీసైక్లింగ్',
    compost: 'కంపోస్ట్',
    landfill: 'లాండ్‌ఫిల్',
    activeRoutes: 'యాక్టివ్ రూట్లు',
    nextCollection: 'తదుపరి సేకరణ స్థితి',
    sustainabilityImpact: 'పర్యావరణ ప్రభావం',
    recentActivity: 'ఇటీవలి కార్యకలాపాలు',
    carbonOffset: 'కార్బన్ తగ్గింపు',
    waterSaved: 'నీటి పొదుపు',
  },
  ta: {
    selectRole: 'உங்கள் பாத்திரத்தைத் தேர்ந்தெடுக்கவும்',
    selectRoleSub: 'நாக்பூர் ஸ்மார்ட் சானிட்டேஷனுக்கு வரவேற்கிறோம்.',
    citizenRole: 'குடிமக்கள் போர்ட்டல்',
    citizenDesc: 'குப்பை புகார்களை பதிவு செய்யவும், வாகனத்தை கண்காணிக்கவும்.',
    adminRole: 'நிர்வாக போர்ட்டல்',
    adminDesc: 'நகராட்சி கண்காணிப்பு மற்றும் மண்டல பகுப்பாய்வு.',
    workerRole: 'பணியாளர் போர்ட்டல்',
    workerDesc: 'தூய்மைப் பணியாளர்களின் பாதை வழிகாட்டல் மற்றும் சேகரிப்பு உறுதிப்படுத்தல்.',
    enterPortal: 'போர்ட்டலில் நுழையவும்',
    switchRole: 'பாத்திரத்தை மாற்றவும்',
    darkMode: 'டார்க் மோட்',
    lightMode: 'லைட் மோட்',
    language: 'மொழி',
    settings: 'அமைப்புகள்',
    ecoPulse: 'ஈகோ பல்ஸ்',
    ecoPulseMsg: '2026-க்குள் 100% கழிவு மாற்றம் நாக்பூரின் இலக்கு.',
    overview: 'மேலோட்டம்',
    dashboard: 'டாஷ்போர்டு',
    analytics: 'பகுப்பாய்வு',
    reportWaste: 'குப்பையைப் புகாரளி',
    myGrievances: 'என் புகார்கள்',
    liveTracker: 'நேரடி லாரி கண்காணிப்பு',
    weeklySchedule: 'வாராந்திர அட்டவணை',
    greenPoints: 'கிரீன் பாயிண்ட்ஸ் சன்மானம்',
    segregationGuide: 'கழிவு பிரிப்பு வழிகாட்டி',
    grievanceDispatch: 'புகார் தீர்வு',
    fleetManagement: 'வாகன மேலாண்மை',
    workerRegistry: 'பணியாளர் பதிவேடு',
    zoneManagement: 'மண்டல மேலாண்மை',
    auditReports: 'தணிக்கை அறிக்கைகள்',
    platformSettings: 'தள அமைப்புகள்',
    myDashboard: 'என் டாஷ்போர்டு',
    myRouteMap: 'என் பாதை வரைபடம்',
    binChecklist: 'குப்பை தொட்டி சரிபார்ப்பு',
    shiftHistory: 'பணி நேர வரலாறு',
    workerProfile: 'பணியாளர் சுயவிவரம்',
    contactSupport: 'தொடர்பு கொள்ளவும்',
    viewReports: 'அறிக்கைகளைப் பார்',
    exportPdf: 'PDF பதிவிறக்கம்',
    generateInsights: 'பகுப்பாய்வு செய்',
    reportWasteNow: 'இப்போதே புகாரளி',
    wasteDiverted: 'மறுசுழற்சி கழிவு',
    recycling: 'மறுசுழற்சி',
    compost: 'உரம்',
    landfill: 'கழிவுநிலம்',
    activeRoutes: 'செயலில் உள்ள பாதைகள்',
    nextCollection: 'அடுத்த சேகரிப்பு நிலை',
    sustainabilityImpact: 'சுற்றுச்சூழல் தாக்கம்',
    recentActivity: 'சமீபத்திய நடவடிக்கைகள்',
    carbonOffset: 'கார்பன் சேமிப்பு',
    waterSaved: 'நீர் சேமிப்பு',
  },
  gu: {
    selectRole: 'તમારી ભૂમિકા પસંદ કરો',
    selectRoleSub: 'નાગપુર સ્માર્ટ સેનિટેશનમાં આપનું સ્વાગત છે.',
    citizenRole: 'નાગરિક પોર્ટલ',
    citizenDesc: 'કચરાની ફરિયાદો નોંધાવો, ટ્રક ટ્રેક કરો, ગ્રીનપોઇન્ટ્સ મેળવો.',
    adminRole: 'વહીવટી પોર્ટલ',
    adminDesc: 'મ્યુનિસિપલ મોનિટરિંગ, ફ્લીટ ટ્રેકિંગ અને ઝોન એનાલિટિક્સ.',
    workerRole: 'કર્મચારી પોર્ટલ',
    workerDesc: 'સફાઈ કર્મચારી રૂટ નેવિગેશન અને બિન કલેક્શન કન્ફર્મેશન.',
    enterPortal: 'પોર્ટલમાં પ્રવેશ કરો',
    switchRole: 'ભૂમિકા બદલો',
    darkMode: 'ડાર્ક મોડ',
    lightMode: 'લાઇટ મોડ',
    language: 'ભાષા',
    settings: 'સેટિંગ્સ',
    ecoPulse: 'ઇકો પલ્સ',
    ecoPulseMsg: 'નાગપુરનું લક્ષ્ય 2026 સુધીમાં 100% વેસ્ટ ડાયવર્ઝન છે.',
    overview: 'ઓવરવ્યૂ',
    dashboard: 'ડેશબોર્ડ',
    analytics: 'એનાલિટિક્સ',
    reportWaste: 'કચરાની ફરિયાદ કરો',
    myGrievances: 'મારી ફરિયાદો',
    liveTracker: 'લાઇવ ટ્રક ટ્રેકર',
    weeklySchedule: 'સાપ્તાહિક સમયપત્રક',
    greenPoints: 'ગ્રીનપોઇન્ટ્સ ઇનામ',
    segregationGuide: 'કચરા વર્ગીકરણ માર્ગદર્શિકા',
    grievanceDispatch: 'ફરિયાદ નિવારણ',
    fleetManagement: 'વાહન વ્યવસ્થાપન',
    workerRegistry: 'કર્મચારી રજિસ્ટર',
    zoneManagement: 'ઝોન વ્યવસ્થાપન',
    auditReports: 'ઓડિટ અહેવાલો',
    platformSettings: 'સિસ્ટમ સેટિંગ્સ',
    myDashboard: 'મારું ડેશબોર્ડ',
    myRouteMap: 'મારો રૂટ મેપ',
    binChecklist: 'કચરાપેટી ચેકલિસ્ટ',
    shiftHistory: 'શિફ્ટ ઇતિહાસ',
    workerProfile: 'કર્મચારી પ્રોફાઇલ',
    contactSupport: 'સંપર્ક કરો',
    viewReports: 'અહેવાલો જુઓ',
    exportPdf: 'PDF ડાઉનલોડ',
    generateInsights: 'વિશ્લેષણ કરો',
    reportWasteNow: 'હમણાં જ ફરિયાદ કરો',
    wasteDiverted: 'પુનઃઉપયોગી કચરો',
    recycling: 'રિસાયક્લિંગ',
    compost: 'ખાતર',
    landfill: 'લેન્ડફિલ',
    activeRoutes: 'સક્રિય રૂટ',
    nextCollection: 'આગામી કલેક્શન સ્ટેટસ',
    sustainabilityImpact: 'પર્યાવરણીય અસર',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    carbonOffset: 'કાર્બન બચત',
    waterSaved: 'પાણી બચત',
  },
  kn: {
    selectRole: 'ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    selectRoleSub: 'ನಾಗ್ಪುರ ಸ್ಮಾರ್ಟ್ ಸ್ಯಾನಿಟೇಷನ್‌ಗೆ ಸುಸ್ವಾಗತ.',
    citizenRole: 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
    citizenDesc: 'ತ್ಯಾಜ್ಯ ದೂರುಗಳನ್ನು ಸಲ್ಲಿಸಿ, ಟ್ರ್ಯಾಕ್ ಮಾಡಿ, ಗ್ರೀನ್‌ಪಾಯಿಂಟ್ಸ್ ಗಳಿಸಿ.',
    adminRole: 'ಆಡಳಿತಾತ್ಮಕ ಪೋರ್ಟಲ್',
    adminDesc: 'ಪೌರಕಾರ್ಮಿಕ ಮೇಲ್ವಿಚಾರಣೆ ಮತ್ತು ವಲಯ ವಿಶ್ಲೇಷಣೆ.',
    workerRole: 'ಪೌರಕಾರ್ಮಿಕ ಪೋರ್ಟಲ್',
    workerDesc: 'ನೈರ್ಮಲ್ಯ ಕಾರ್ಮಿಕರ ಮಾರ್ಗ ಸಂಚಾರ ಮತ್ತು ಸಂಗ್ರಹಣೆ ದೃಢೀಕರಣ.',
    enterPortal: 'ಪೋರ್ಟಲ್‌ಗೆ ಪ್ರವೇಶಿಸಿ',
    switchRole: 'ಪಾತ್ರವನ್ನು ಬದಲಾಯಿಸಿ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    lightMode: 'ಲೈಟ್ ಮೋಡ್',
    language: 'ಭಾಷೆ',
    settings: 'ಸೇಟಿಂಗ್ಸ್',
    ecoPulse: 'ಈಕೋ ಪಲ್ಸ್',
    ecoPulseMsg: '2026 ರ ವೇಳೆಗೆ 100% ತ್ಯಾಜ್ಯ ಮರುಬಳಕೆ ನಾಗ್ಪುರದ ಗುರಿಯಾಗಿದೆ.',
    overview: 'ಅವಲೋಕನ',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    analytics: 'ವಿಶ್ಲೇಷಣೆ',
    reportWaste: 'ತ್ಯಾಜ್ಯ ದೂರು ನೀಡಿ',
    myGrievances: 'ನನ್ನ ದೂರುಗಳು',
    liveTracker: 'ಲೈವ್ ಟ್ರಕ್ ಟ್ರ್ಯಾಕರ್',
    weeklySchedule: 'ವಾರದ ವೇಳಾಪಟ್ಟಿ',
    greenPoints: 'ಗ್ರೀನ್‌ಪಾಯಿಂಟ್ಸ್ ಬಹುಮಾನಗಳು',
    segregationGuide: 'ತ್ಯಾಜ್ಯ ವಿಂಗಡಣೆ ಮಾರ್ಗದರ್ಶಿ',
    grievanceDispatch: 'ದೂರು ಪರಿಹಾರ',
    fleetManagement: 'ವಾಹನ ನಿರ್ವಹಣೆ',
    workerRegistry: 'ಸಿಬ್ಬಂದಿ ನೋಂದಣಿ',
    zoneManagement: 'ವಲಯ ನಿರ್ವಹಣೆ',
    auditReports: 'ವರದಿಗಳು',
    platformSettings: 'ಸಿಸ್ಟಮ್ ಸೇಟಿಂಗ್ಸ್',
    myDashboard: 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    myRouteMap: 'ನನ್ನ ಮಾರ್ಗ ನಕ್ಷೆ',
    binChecklist: 'ಕಸದ ತೊಟ್ಟಿ ಪಟ್ಟಿ',
    shiftHistory: 'ಶಿಫ್ಟ್ ಇತಿಹಾಸ',
    workerProfile: 'ಸಿಬ್ಬಂದಿ ಪ್ರೊಫೈಲ್',
    contactSupport: 'ಸಂಪರ್ಕಿಸಿ',
    viewReports: 'ವರದಿ ನೋಡಿ',
    exportPdf: 'PDF ಡೌನ್‌ಲೋಡ್',
    generateInsights: 'ವಿಶ್ಲೇಷಿಸಿ',
    reportWasteNow: 'ಈಗಲೇ ದೂರು ನೀಡಿ',
    wasteDiverted: 'ಮರುಬಳಕೆಯಾದ ತ್ಯಾಜ್ಯ',
    recycling: 'ಮರುಬಳಕೆ',
    compost: 'ಗೊಬ್ಬರ',
    landfill: 'ಲ್ಯಾಂಡ್‌ಫಿಲ್',
    activeRoutes: 'ಸಕ್ರಿಯ ಮಾರ್ಗಗಳು',
    nextCollection: 'ಮುಂದಿನ ಸಂಗ್ರಹಣೆ ಸ್ಥಿತಿ',
    sustainabilityImpact: 'ಪರಿಸರ ಪ್ರಭಾವ',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    carbonOffset: 'ಕಾರ್ಬನ್ ಉಳಿತಾಯ',
    waterSaved: 'ನೀರು ಉಳಿತಾಯ',
  },
  ml: {
    selectRole: 'നിങ്ങളുടെ റോൾ തിരഞ്ഞെടുക്കുക',
    selectRoleSub: 'നാഗ്പൂർ സ്മാർട്ട് സാനിറ്റേഷനിലേക്ക് സ്വാഗതം.',
    citizenRole: 'പൗരന്മാരുടെ പോർട്ടൽ',
    citizenDesc: 'മാലിന്യ പരാതികൾ സമർപ്പിക്കുക, വാഹനം ട്രാക്ക് ചെയ്യുക.',
    adminRole: 'അഡ്മിനിസ്ട്രേറ്റീവ് പോർട്ടൽ',
    adminDesc: 'മുനിസിപ്പൽ മേൽനോട്ടവും ഫ്ലീറ്റ് ട്രാക്കിംഗും.',
    workerRole: 'തൊഴിലാളി പോർട്ടൽ',
    workerDesc: 'ശുചീകരണ തൊഴിലാളികളുടെ റൂട്ട് നാവിഗേഷൻ.',
    enterPortal: 'പോർട്ടലിൽ പ്രവേശിക്കുക',
    switchRole: 'റോൾ മാറ്റുക',
    darkMode: 'ഡാർക്ക് മോഡ്',
    lightMode: 'ലൈറ്റ് മോഡ്',
    language: 'ഭാഷ',
    settings: 'സജ്ജീകരണങ്ങൾ',
    ecoPulse: 'ഈക്കോ പൾസ്',
    ecoPulseMsg: '2026 ഓടെ 100% മാലിന്യ സംസ്കരണം നാഗ്പൂരിന്റെ ലക്ഷ്യമാണ്.',
    overview: 'അവലോകനം',
    dashboard: 'ഡാഷ്ബോർഡ്',
    analytics: 'വിശകലനം',
    reportWaste: 'മാലിന്യ പരാതി സമർപ്പിക്കുക',
    myGrievances: 'എന്റെ പരാതികൾ',
    liveTracker: 'ലൈവ് ട്രക്ക് ട്രാക്കർ',
    weeklySchedule: 'വാരാന്ത്യ ടൈംടേബിൾ',
    greenPoints: 'ഗ്രീൻ പോയിന്റുകൾ',
    segregationGuide: 'മാലിന്യ വർഗ്ഗീകരണ ഗൈഡ്',
    grievanceDispatch: 'പരാതി പരിഹാരം',
    fleetManagement: 'വാഹന മാനേജ്മെന്റ്',
    workerRegistry: 'തൊഴിലാളി രജിസ്ട്രി',
    zoneManagement: 'സോൺ മാനേജ്മെന്റ്',
    auditReports: 'ഓഡിറ്റ് റിപ്പോർട്ടുകൾ',
    platformSettings: 'സിസ്റ്റം സജ്ജീകരണങ്ങൾ',
    myDashboard: 'എന്റെ ഡാഷ്ബോർഡ്',
    myRouteMap: 'എന്റെ റൂട്ട് മാപ്പ്',
    binChecklist: 'ബിൻ ചെക്ക്ലിസ്റ്റ്',
    shiftHistory: 'ഷിഫ്റ്റ് ചരിത്രം',
    workerProfile: 'തൊഴിലാളി പ്രൊഫൈൽ',
    contactSupport: 'ബന്ധപ്പെടുക',
    viewReports: 'റിപ്പോർട്ടുകൾ കാണുക',
    exportPdf: 'PDF ഡൗൺലോഡ്',
    generateInsights: 'വിശകലനം ചെയ്യുക',
    reportWasteNow: 'ഇപ്പോൾ പരാതിപ്പെടുക',
    wasteDiverted: 'പുനരുപയോഗിച്ച മാലിന്യം',
    recycling: 'റീസൈക്ലിംഗ്',
    compost: 'കമ്പോസ്റ്റ്',
    landfill: 'ലാൻഡ്ഫിൽ',
    activeRoutes: 'ആക്ടീവ് റൂട്ടുകൾ',
    nextCollection: 'അടുത്ത ശേഖരണ നില',
    sustainabilityImpact: 'പരിസ്ഥിതി ആഘാതം',
    recentActivity: 'സമീപകാല പ്രവർത്തനങ്ങൾ',
    carbonOffset: 'കാർബൺ ലാഭം',
    waterSaved: 'ജല ലാഭം',
  },
  pa: {
    selectRole: 'ਆਪਣੀ ਭੂਮਿਕਾ ਚੁਣੋ',
    selectRoleSub: 'ਨਾਗਪੁਰ ਸਮਾਰਟ ਸੈਨੀਟੇਸ਼ਨ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ।',
    citizenRole: 'ਨਾਗਰਿਕ ਪੋਰਟਲ',
    citizenDesc: 'ਕੂੜੇ ਦੀਆਂ ਸ਼ਿਕਾਇਤਾਂ ਦਰਜ ਕਰੋ, ਟ੍ਰੈਕ ਕਰੋ, ਗ੍ਰੀਨ ਪੁਆਇੰਟ ਪ੍ਰਾਪਤ ਕਰੋ।',
    adminRole: 'ਪ੍ਰਸ਼ਾਸਕੀ ਪੋਰਟਲ',
    adminDesc: 'ਨਗਰ ਨਿਗਮ ਨਿਗਰਾਨੀ ਅਤੇ ਫਲੀਟ ਟਰੈਕਿੰਗ।',
    workerRole: 'ਕਰਮਚਾਰੀ ਪੋਰਟਲ',
    workerDesc: 'ਸਫ਼ਾਈ ਕਰਮਚਾਰੀ ਰੂਟ ਨੇਵੀਗੇਸ਼ਨ ਅਤੇ ਸੰਗ੍ਰਹਿ ਦੀ ਪੁਸ਼ਟੀ।',
    enterPortal: 'ਪੋਰਟਲ ਵਿੱਚ ਦਾਖਲ ਹੋਵੋ',
    switchRole: 'ਭੂਮਿਕਾ ਬਦਲੋ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    lightMode: 'ਲਾਈਟ ਮੋਡ',
    language: 'ਭਾਸ਼ਾ',
    settings: 'ਸੈਟਿੰਗਾਂ',
    ecoPulse: 'ਈਕੋ ਪਲਸ',
    ecoPulseMsg: 'ਨਾਗਪੁਰ ਦਾ ਟੀਚਾ 2026 ਤੱਕ 100% ਕੂੜਾ ਨਿਪਟਾਰਾ ਹੈ।',
    overview: 'ਸੰਖੇਪ',
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',
    reportWaste: 'ਕੂੜੇ ਦੀ ਸ਼ਿਕਾਇਤ ਕਰੋ',
    myGrievances: 'ਮੇਰੀਆਂ ਸ਼ਿਕਾਇਤਾਂ',
    liveTracker: 'ਲਾਈਵ ਟਰੱਕ ਟਰੈਕਰ',
    weeklySchedule: 'ਹਫ਼ਤਾਵਾਰੀ ਸਮਾਂ-ਸਾਰਣੀ',
    greenPoints: 'ਗ੍ਰੀਨ ਪੁਆਇੰਟ ਇਨਾਮ',
    segregationGuide: 'ਕੂੜਾ ਵੱਖ ਕਰਨ ਦਾ ਗਾਈਡ',
    grievanceDispatch: 'ਸ਼ਿਕਾਇਤ ਨਿਪਟਾਰਾ',
    fleetManagement: 'ਗੱਡੀਆਂ ਦਾ ਪ੍ਰਬੰਧਨ',
    workerRegistry: 'ਕਰਮਚਾਰੀ ਰਜਿਸਟਰ',
    zoneManagement: 'ਜ਼ੋਨ ਪ੍ਰਬੰਧਨ',
    auditReports: 'ਰਿਪੋਰਟਾਂ',
    platformSettings: 'ਸਿਸਟਮ ਸੈਟਿੰਗਾਂ',
    myDashboard: 'ਮੇਰਾ ਡੈਸ਼ਬੋਰਡ',
    myRouteMap: 'ਮੇਰਾ ਰੂਟ ਮੈਪ',
    binChecklist: 'ਕੂੜੇਦਾਨ ਸੂਚੀ',
    shiftHistory: 'ਸ਼ਿਫਟ ਇਤਿਹਾਸ',
    workerProfile: 'ਕਰਮਚਾਰੀ ਪ੍ਰੋਫਾਈਲ',
    contactSupport: 'ਸੰਪਰਕ ਕਰੋ',
    viewReports: 'ਰਿਪੋਰਟਾਂ ਦੇਖੋ',
    exportPdf: 'PDF ਡਾਊਨਲੋਡ',
    generateInsights: 'ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
    reportWasteNow: 'ਹੁਣੇ ਸ਼ਿਕਾਇਤ ਕਰੋ',
    wasteDiverted: 'ਮੁੜ-ਵਰਤੋਂਯੋਗ ਕੂੜਾ',
    recycling: 'ਰਿਸਾਈਕਲਿੰਗ',
    compost: 'ਖਾਦ',
    landfill: 'ਲੈਂਡਫਿਲ',
    activeRoutes: 'ਐਕਟਿਵ ਰੂਟ',
    nextCollection: 'ਅਗਲੀ ਚੁੱਕਣ ਦੀ ਸਥਿਤੀ',
    sustainabilityImpact: 'ਵਾਤਾਵਰਣ ਪ੍ਰਭਾਵ',
    recentActivity: 'ਤਾਜ਼ਾ ਗਤੀਵਿਧੀ',
    carbonOffset: 'ਕਾਰਬਨ ਬਚਤ',
    waterSaved: 'ਪਾਣੀ ਬਚਤ',
  },
};
